### ISSUE TITLE
关于steam登录的一些小问题

### ISSUE THREAD

**Issue by LiuXianBang** [13060923171/js-crwal#1]
我像您一样将steam登录的加密的代码扒下来，并且能生成密码
但我无论如何post我的包进行login的时候 都会显示密码错误
请问您有无遇到类似的问题 期待能与您联系

**Comment by 13060923171** [comment]
这个问题我没有遇到，可能平台上面的规则有变动，自然就出错，你要自己慢慢去看你的解密过程才能得得知




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "13060923171/js-crwal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月11日(星期三) 下午3:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[13060923171/js-crwal] 关于steam登录的一些小问题 (#1)





 
我像您一样将steam登录的加密的代码扒下来，并且能生成密码
 但我无论如何post我的包进行login的时候 都会显示密码错误
 请问您有无遇到类似的问题 期待能与您联系
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LiuXianBang** [comment]
我已经研究了很久了，确实是把整个js都扒下来了。伪造的包也和原来的包没有差别 但是仍不知道出现什么问题
希望您能抽空再去试验一下
